### ISSUE TITLE
Feature: Implement Challenge encounters.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/CommunityKitPublic#18]
Who is the toughest party in the dungeon? I'll find out by allowing people to challenge each other.

**Comment by ZaneDubya** [comment]
Added _ChallengeMode variable to XPT.WorldData.Battle.Encounter

**Comment by ZaneDubya** [comment]
I just cannot. This is too big an issue. Deferring.

**Comment by ZaneDubya** [comment]
Again, issue is too big. Deferring.

**Comment by ZaneDubya** [comment]
It is possible this will be ready for release, but it is big enough that it might, on its own, delay release by a week. Unfortunately, I have to de-prioritize this in favor of getting ready for release. Deferring to future features.

**Comment by alerum68** [comment]
Suggestion: create Hall of heros for challenge battles, showing stats for win, loss, and percentage. Show these stats for solo, group leader, and regular group member.

**Comment by ZaneDubya** [comment]
Done! Needs UI
