### ISSUE TITLE
Mana restore not restoring mana

### ISSUE THREAD

**Issue by Tevish** [ZaneDubya/CommunityKitPublic#264]
I'm getting the message that my mana is restored but I'm sitting at 0 mana using mana restore. Mana elixir will replenish 90 mana.

**Comment by ZaneDubya** [comment]
Nice find! I must be incorrectly reading the source data for Mana Restores... because the Mana Restore potion is actually subtracting 56 mana points from your current mana!! I'll figure out what's going on here!

**Comment by ZaneDubya** [comment]
Fixed locally, will push to the server this evening. Thank you!!!
