### ISSUE TITLE
Death after shield expires

### ISSUE THREAD

**Issue by Tevish** [ZaneDubya/CommunityKitPublic#265]
I was fighting silver ogres in the mausoleum and after my shield spell drops I die, even if the opponent misses.

**Comment by ZaneDubya** [comment]
This is an interesting find! I will see if I can replicate it on my end. Thank you for reporting it!

**Comment by ZaneDubya** [comment]
Hey @Tevish, I have fixed #277, which I think may have caused this bug (being shielded and being petrified are handled in very similar ways). Please post a new issue if this comes up again - and please post pictures of the combat round where this happened, if possible. Thank you!!
