### ISSUE TITLE
Attributes in Guildhall show 0

### ISSUE THREAD

**Issue by Tevish** [ZaneDubya/CommunityKitPublic#338]
I was leveling a chaos and harmony aligned pair in the harmony challenge in the great corridor. The chaos character, after going to the guildhall and leveling up, showed 0 stats in both strength and defense.

Log out and log in did not fix the guildhall. The info tab still seems to be correct when in the volcano.

**Comment by ZaneDubya** [comment]
Hey @Tevish! What is your character name?

**Comment by Tevish** [comment]
It was on Ylith :)

**Comment by ZaneDubya** [comment]
I'll look into it! Is it still incorrect in the keep?

**Comment by ZaneDubya** [comment]
I'll need to add some more debug/admin features to test this and (hopefully!) fix it. I'll try to have it in by next week. :)

**Comment by ZaneDubya** [comment]
@Tevish I'm sorry, it looks like you triggered the stat reducing effects of the great corridor. That really sucks. Sorry :(

**Comment by Tevish** [comment]
Oops! I’m guessing it’s permenant?

Sent from my iPhone.

On Apr 20, 2019, at 11:32 AM, Zane Wagner <notifications@github.com<mailto:notifications@github.com>> wrote:


@Tevish<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTevish&data=02%7C01%7C%7C7925d2b5b9254bfa981308d6c5a56f89%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636913711657187290&sdata=wYBGcQDajJZfWbQM5Aga52CfqqMGeaf3LdnyvgLyvoA%3D&reserved=0> I'm sorry, it looks like you triggered the stat reducing effects of the great corridor. That really sucks. Sorry :(

**Comment by ZaneDubya** [comment]
While I don't want to toy with the original game mechanics too much, I am getting rid of this permanent stat reducing effect. It is bad game design. Would you contact me in game the next time you see me (ZaneDubya)?
