### ISSUE TITLE
Attack first available Mob with right click

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#351]
Right clicking on the Axe/Sword icon will cause an automatic attack on the first available mob, attempting slot 1 first, and if no mob is present to attack slot 2.  Since all slots eventually slide into one of these two slots, there would be no need to have this feature try other slots.

**Comment by ZaneDubya** [comment]
I think I could do something like this fairly easily. Maybe Shift-Click instead of Right click, because I still use right click in a few places to show a help message.

**Comment by ZaneDubya** [comment]
@alerum68 I hope the new combat hotkeys are sufficient :)
