### ISSUE TITLE
Tooltip text cut off: "Protects Against "

### ISSUE THREAD

**Issue by evilevilbob** [ZaneDubya/CommunityKitPublic#356]
![image](https://user-images.githubusercontent.com/49768306/56395305-ae47b300-61ff-11e9-9a3b-48fa1fe2fda3.png)

The "Protects against" text is incomplete.  Saw the same on the Shield of Life as well.

**Comment by ZaneDubya** [comment]
@evilevilbob What does it protect against! Who knows?! :)

**Comment by ZaneDubya** [comment]
Prioritizing this - will have it fixed tomorrow.

**Comment by ZaneDubya** [comment]
Fixed!
