### ISSUE TITLE
Chat messages indicate that you have died when hit by Tempest winds

### ISSUE THREAD

**Issue by evilevilbob** [ZaneDubya/CommunityKitPublic#357]
Attached video demonstrates.  I believe this also occurs at the damage events higher in the labyrinth.

[MedievaLands 2019-04-17 18-30-55.zip](https://github.com/ZaneDubya/CommunityKitPublic/files/3096393/MedievaLands.2019-04-17.18-30-55.zip)

**Comment by ZaneDubya** [comment]
This is totally bizarre. I can't replicate it.

**Comment by ZaneDubya** [comment]
The event code here does 100 damage and then checks your current health. If it is above 0, it jumps to the end of the routine. If it is 0, then it shows the "You have died." message. But your health is obviously above zero. The "you have died." message is intrinsic to the routine - so it's not being triggered by anywhere else in the code. I have no idea why this is being triggered.

**Comment by evilevilbob** [comment]
I'm wondering if this might have started after I died of poison while
walking. Perhaps some kind of trigger related to that got stuck and this
sets it off too? Speculating! Can test further this eve probably.

**Comment by ZaneDubya** [comment]
Hey bob! Have you seen this pop up recently?

**Comment by ZaneDubya** [comment]
yup, still happening. map 24 tile 15 15

**Comment by ZaneDubya** [comment]
Ok looks good!
