### ISSUE TITLE
Mana / Health Increase in Battle - Text Color

### ISSUE THREAD

**Issue by rbodor** [ZaneDubya/CommunityKitPublic#376]
When using a potion to increase mana or health in battle the text is black vs purple for Mana and Blue for health

**Comment by rbodor** [comment]
Found under features of battle text

**Comment by ZaneDubya** [comment]
@rbodor Thanks for the reminder! I'll see if I can't fit this into the release coming out today.

**Comment by ZaneDubya** [comment]
Also welcome to GitHub!

**Comment by rbodor** [comment]
Absolutely!  The game has been awesome, I used to play this back when I was
14 and now I'm nearing my 40s! :)   I'm a C/C++ developer along with C#,
not that you need any help, but I'll help in any way I can!

**Comment by ZaneDubya** [comment]
Thanks! If you run into any crash bugs, you'll see a stack trace in the logs - please post those here!

**Comment by ZaneDubya** [comment]
You and me both btw - I played when I was 8 and have been thinking of remaking it ever since 1996. I realized I finally knew enough to get it done last year, and here we are. :)

**Comment by rbodor** [comment]
You got it!  Thanks again!

**Comment by ZaneDubya** [comment]
You and me both btw - I played when I was 8 and have been thinking of remaking it ever since 1996. I realized I finally knew enough to get it done last year, and here we are. :)

**Comment by rbodor** [comment]
You did what people talked about wanting to do for 15+ years now!!  I know
the whole community really appreciates it!
