### ISSUE TITLE
Rune Quest doesn't open teleport to Castle Parapets from Castle Wizard's Room

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#387]
After spelling out ARNAKKIAN, ENLIKIL, and GHOST two things should happen.

1) A Teleport to another location of Level 6: Castle Parapets should be available after spelling GHOST.
2) The next time you try to use the Runes, you should only need to spell GHOST to activate the teleport.

Currently spelling out the words will not activate the teleport to the Parapets, but instead becomes just another door back into the Castle Wizard's Room as if you just went through GHOST without spelling the other two words.

**Comment by ZaneDubya** [comment]
Ah yes, the spelling challenge - one of the only scripts in the game that I don't really understand.
- Map here: [Link](https://github.com/ZaneDubya/YserbiusData/blob/87aa7fc126627f4a2e42728bfd11c8c51a1a399d/Maps/YsMap23-events.png)
- Event script here: [Link](https://github.com/ZaneDubya/YserbiusData/blob/87aa7fc126627f4a2e42728bfd11c8c51a1a399d/Maps/YsMap23.cs)

- Is this new as of today or the first time you have tried it?
- Is the message associated with this event something like "Both Arnakkian and Enlikil have been identified. he Ghost takes you to the Guardians." ?
- You are correct that after spelling A and E, those events are always set.
- When you say that the teleport "becomes another door back into the CWR" - do you mean that you just pass through the wall?

**Comment by ZaneDubya** [comment]
Fixed in next version
