### ISSUE TITLE
Opening menus in combat resets option to flee

### ISSUE THREAD

**Issue by evilevilbob** [ZaneDubya/CommunityKitPublic#388]
When you fail to flee, the flee button becomes greyed out.
If you open a menu (Spells, Skills, Items), then close the menu, the flee button is lit again and you can keep attempting to flee until successful.

**Comment by ZaneDubya** [comment]
haha no kidding! What a fun bug you discovered.

**Comment by ZaneDubya** [comment]
Fixed
