### ISSUE TITLE
Infinite Armor has -56 Armor Rating

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#392]
Infinite Armor has a negative armor value.  -56.

**Comment by ZaneDubya** [comment]
That item has 200 damage reduction! Is that a joke? That seems way too high.

**Comment by ZaneDubya** [comment]
Fixed!

**Comment by alerum68** [comment]
Nope, that sounds right... it makes you very hard to hit.  Best armor in the game.
