### ISSUE TITLE
Passing Equipment

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#393]
In 2.0 of the original Yserbius the passing of equipment was allowed, with the exception of Quest Items.  It was removed in 2.1 and later because of the bug where you could pass an item, and reboot and go link dead without saving.  When you logged back on, both you and the person you passed the item to would have a copy.  With the new code, I think we should bring back the passing of equipment, as long as spawning trick isn't replicated.

**Comment by ZaneDubya** [comment]
Please see https://github.com/ZaneDubya/YserbiusData/blob/master/Data/Items.csv

There is already a CanTrade data field for each item. Does this not correspond with which items you think should be traded? If not, can you submit a pull request with just that one field changed?

**Comment by alerum68** [comment]
The CanTrade field was only limited to actual Quest Items not being traded.  Passing of any other type of equipment, and was allowed.  Because of the bug mentioned above, the majority of equipment people were using was spawned.

**Comment by ZaneDubya** [comment]
Leaving this as is. I want people to have to work for the good stuff!
