### ISSUE TITLE
Empty Battle in Solider's Quarters

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#394]
![image](https://user-images.githubusercontent.com/35239228/56876518-d0f67a80-69fc-11e9-9b84-77808335ffce.png)
![image](https://user-images.githubusercontent.com/35239228/56876545-026f4600-69fd-11e9-8d73-a26311886945.png)

**Comment by ZaneDubya** [comment]
Sorry about that! Thank you!

**Comment by ZaneDubya** [comment]
So much for "almost empty" eh? Working on this now.

**Comment by ZaneDubya** [comment]
private void FnGOLDFENC_10(ServerPlayer player, bool isForwardMove) {
            int ax = 0, bx = 0, cx = 0, dx = 0, si = 0, di = 0, tmp = 0;
            L0000: // BEGIN;
            L0003: Compare(GetFlag(player, FlagTypeDungeon, FlagSoldiersQuartersSnakeGold), 0x0001);
            L0017: if (JumpNotEqual) goto L0047;
            L0019: ShowMessage(player, String063A); // You stumble upon an almost empty nesting area.
            L0026: AddTreasure(player, 0x0000, 0x00, 0x00, 0x00, 0x00, 0xCB);
            L0044: goto L0122;
            L0047: AddTreasure(player, 0x05DC, 0x00, 0x00, 0x00, 0x00, 0xCB);
            L0066: ShowMessage(player, String0669); // Angry hissing distracts you as you reach down for some gold coins.
            L0073: SetFlag(player, FlagTypeDungeon, FlagSoldiersQuartersSnakeGold, 0x01);
            L0088: Compare(PartyCount(player), 0x0001);
            L0093: if (JumpEqual) goto L00A2;
            L0095: Compare(PartyCount(player), 0x0002);
            L00A0: if (JumpNotEqual) goto L00C8;
            L00A2: AddEncounter(player, 0x01, 0x07);
            L00B4: AddEncounter(player, 0x02, 0x06);
            L00C6: goto L0122;
            L00C8: AddEncounter(player, 0x01, 0x06);
            L00DA: AddEncounter(player, 0x02, 0x06);
            L00EC: AddEncounter(player, 0x03, 0x07);
            L00FE: AddEncounter(player, 0x04, 0x07);
            L0110: AddEncounter(player, 0x05, 0x06);
            L0122: return; // RETURN;
        }

L0044 is the bad line. Changing this to 

L0044: goto L0088;

Fixed!

**Comment by alerum68** [comment]
Lol! Shouldn't have said anything and kept getting the free treasure.
