### ISSUE TITLE
Rapidly attacking with A + Click causes me to return to the main menu.

### ISSUE THREAD

**Issue by XLR-XR** [ZaneDubya/CommunityKitPublic#404]
macOS 10.12.6. 

Pressing _A Click A Click A Click_ results in being booted to the main menu.
A video of this in action: https://streamable.com/6rfie

Also happens seemingly randomly in normal combat if you play long enough.
Just happened again, but this time I got an error of some sort? https://i.imgur.com/NtoAB2K.png

**Comment by ZaneDubya** [comment]
Thanks for submitting this! I'll fix it promptly.

**Comment by ZaneDubya** [comment]
Fixed, will push later today. :) Thanks again @XLR-XR
