### ISSUE TITLE
Furtive Skill not working

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#407]
Furtive Skill will allow you to hit enemies in the back row.  I have furtive trained to level 10 and this is the message I recieved when trying to attack:

![image](https://user-images.githubusercontent.com/35239228/57119333-365cab00-6d1e-11e9-80c4-c8c330ff5e43.png)

**Comment by ZaneDubya** [comment]
I'll take a look at it :)

**Comment by ZaneDubya** [comment]
Ok, fixed! You need to use the skill in combat. You'll see the message "You prepare a sly attack."
