### ISSUE TITLE
Zaika: add number keys to select monsters.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/CommunityKitPublic#409]

**Comment by alerum68** [comment]
Would this be used only for the attack icon, or would it be done after selection as well... so in theory you can select action then target:

A plus 1 will use attack on spot 1.
Click on Blast and typing 5 will cast blast on mob in spot 5.

Or would it be to select action and spot in one action... typing 1 will cause a normal attack on spot one?

**Comment by jerryblade** [comment]
They way we discussed it would be the # would be after attack or cast or whatever so you could use it for anything where a target is required. I agree that this would be the most useful implementation.

**Comment by jerryblade** [comment]
0 for self target would be good start. Especially playing solo, lots and lots of self casts and self skills :)

**Comment by ZaneDubya** [comment]
Not adding this at this time, may revisit in the future.
