### ISSUE TITLE
Incorrect teleport

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#411]
In Land of Giants Map, TP at the spot where the mouse pointer is located in the photo takes you to the wrong location:  
![image](https://user-images.githubusercontent.com/35239228/57182916-4083c400-6e5a-11e9-8862-d9cbb24ea3dd.png)

Teleport is in first explored area on lower right of map.  It should take you a spot about 4 or 5 tiles left from bottom right corner, on the bottom row, which will bring you to River of Eternity.

**Comment by ZaneDubya** [comment]
@alerum68 is it the square on the automap where you're currently located?

**Comment by alerum68** [comment]
No, I can't get to the correct location to arrive. I'll have to show you when available.

**Comment by ZaneDubya** [comment]
Fixed!
