### ISSUE TITLE
Queen of Spades door not opening

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#413]
The "hearts" or Queen door isn't opening.  The series of events is you to go door, it says "I am all hearts!", you face the pit to the west, and use the Queen, where it will say "You shot the Moon!".  After this, turn back to the door and head north.  When I completed the series, and turned north to open the door, I was greeted with "I am all Hearts!" again, and the door doesn't open.

**Comment by ZaneDubya** [comment]
Fixed!
