### ISSUE TITLE
Blue gem not rewarded

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#415]
Blue gem not rewarded after killing Arnakian Quest. Quest works properly and 1 million exp rewarded, but no gem.

**Comment by ZaneDubya** [comment]
Fixed! You'll need to fight Arnakian again.

**Comment by alerum68** [comment]
Fought beat Arnie again, and received two bronze bucklers but no blue gem. Shouldn't matter if I beat it before, because as long as you don't have a gem, you should receive them.

**Comment by ZaneDubya** [comment]
Ugh, sorry. When I wrote "fixed", I meant fixed on my end. I still need to deploy the fix - I like to do that during the day, not evenings when pop is higher :). I'll change my issue responses to reflect this. Again, apologies!
