### ISSUE TITLE
Talos: Barb axe quest does not work.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/CommunityKitPublic#418]
Talos mentioned needing to use a bunch of items (like a silver bar?) to create a bridge across lava to get the Barb axe. But the bridge wasn't working. Painful error, that.

Could someone test to see if this is working?

**Comment by ZaneDubya** [comment]
Verified working. What's all this about using a silver bar, lockpick, cleowyn's key, etc?

**Comment by alerum68** [comment]
You need to use those items at different points.

**Comment by alerum68** [comment]
Is why I've been waiting on it.

**Comment by ZaneDubya** [comment]
That must have been how it worked for the single player version. I've restored the scripts from the multiplayer version, which requires at least two people. Its function is very similar to the Parapets quest.
