### ISSUE TITLE
Change when map scripts send messages to the players.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/CommunityKitPublic#428]
This appears throughout the dungeon. Fixing it is going to be more complicated than just not showing messages on isMoveForward.

![57347163-2d951c00-7106-11e9-80c7-97de5f2746c7](https://user-images.githubusercontent.com/7041719/57381233-23a80300-7170-11e9-87f1-af94c4671b83.png)

alerum68: Only problem is that it displays the script for the first interaction you have with her after you receive the script for completion of the quest.

**Comment by ZaneDubya** [comment]
I have a first draft of this change in local. It seems to work in the DE and Mines, but will need serious testing, as this is a big change to how map events are invoked, particularly as to how and when messages are displayed.

**Comment by alerum68** [comment]
I saw all the changes that were made.... This means every tile is gonna have to be revisited isn't it?

**Comment by ZaneDubya** [comment]
Oh man. You have no idea. That was just the beginning. ;)

Not every tile, necessarily - but a good representative sample across all maps.

This will fix the issue where using a healing potion - or any item, or any spell - in a tile will replay every event in that tile.

**Comment by alerum68** [comment]
With this being triggered on IsMoveForward, will it cause problems with people going backwards or strafing, not popping up messages?

**Comment by ZaneDubya** [comment]
Yes. There needs to be multiple kinds of event invocation types. Right now I just have onEnterTile, onFacing, onFacing+isMoveForward, and encounter. I also need onItemUse, onSkillUse, and onSpellUse, and I need to refactor the onFacing events. This will also help - I hope! - with adding the other games that run on the Yserbius engine.

**Comment by ZaneDubya** [comment]
Prioritizing this.

**Comment by ZaneDubya** [comment]
Improvements:
- Only show messages on skill use if the skill was referenced.
- Only show messages on spell use if the spell was referenced.
- Only show messages on item use if the item was referenced.
