### ISSUE TITLE
Battles on Water

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#433]
On water tiles random encounters are occurring.  Water tiles should be a free space, as a hard battle could strand you in the middle of a river, and being unable to heal, you will die before you reach land again.

**Comment by alerum68** [comment]
There is more going on here.  It's not just on water, but other locations that should be "safe" are having random battles as well.

**Comment by ZaneDubya** [comment]
Could you indicate what other tiles are supposed to be safe? There might be a flag I am ignoring in the map file.

**Comment by ZaneDubya** [comment]
Fixed in 186
