### ISSUE TITLE
Zaika: Add a global chat channel

### ISSUE THREAD

**Issue by jerryblade** [ZaneDubya/CommunityKitPublic#435]
Maybe use /a to access the global or "all" chat channel that would allow the entire server to chat without having to exit the dungeon.

**Comment by alerum68** [comment]
I think this one is in the works as part of the Chat Tabs upgrade.

**Comment by ZaneDubya** [comment]
Prioritizing this now.

**Comment by ZaneDubya** [comment]
Done, use /a to chat globally.

**Comment by ZaneDubya** [comment]
<img width="970" alt="Screen Shot 2019-05-14 at 8 50 37 PM" src="https://user-images.githubusercontent.com/7041719/57743266-f5538780-7689-11e9-85d8-ca812f1a1617.png">

**Comment by ZaneDubya** [comment]
Completed last night, will be ready to deploy this evening.

**Comment by jerryblade** [comment]
Is there any way to make it persistent? I LOVE that you added tabs so we can keep track of different chat channel traffic, but every single time we go from the dungeon to the inn or wherever, the history gets wiped. It would be *awesome* if that carried over until you log off!
