### ISSUE TITLE
Challenge battles: Need to revisit stat maxes for all characters.

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#438]
REVENGE has found that pre-retroactive-stat-max characters that made it through the great corridor doors after the stat max was removed and before the pre-retroactive stat max change was made have approximate +1 to +4 extra strength and defense. This is just a handful of characters. I will fix this before putting in the challenge battles.

Original:
> Need to modify code so each race and class has max stat attributes that cannot be gone beyond.  With the change of increasing max attributes along with the attribute itself when visiting a fountain so it doesn't nerf your character, it's not possible to go beyond the max attributes.  I don't know if it's because I visited some locations that increased attributes, but my str and def are +2 beyond on max after visiting Dragonsbreath, and another fountain.

**Comment by ZaneDubya** [comment]
Could you clarify this - what is the value of your stats, and what is the expected value of your stats?

**Comment by alerum68** [comment]
Anyone who created before the stat cap and increased they're stats beyond Max and visited a fountain to increase stats will have those points extra. May only be a few players this affects.

**Comment by ZaneDubya** [comment]
REVENGE when you have a moment will you please post a picture of your stat screen and deeds window to this post? Thanks!

**Comment by alerum68** [comment]
![image](https://user-images.githubusercontent.com/35239228/57583074-aaffba00-7481-11e9-83d9-ea4cc5629e73.png)

**Comment by alerum68** [comment]
![image](https://user-images.githubusercontent.com/35239228/57583085-ca96e280-7481-11e9-85ad-045839205143.png)

**Comment by alerum68** [comment]
![image](https://user-images.githubusercontent.com/35239228/57583090-d4b8e100-7481-11e9-9b19-646df42f583c.png)

**Comment by alerum68** [comment]
![image](https://user-images.githubusercontent.com/35239228/57583094-dedadf80-7481-11e9-9465-8feca0b4e51c.png)

**Comment by alerum68** [comment]
![image](https://user-images.githubusercontent.com/35239228/57583097-e7331a80-7481-11e9-9d05-6d53cbe97cfb.png)

**Comment by ZaneDubya** [comment]
I found the bug that gave rise to this issue. You were right: it's an edge case for players that increased their stats over the max AND viewed the tapestries in the great corridor before the retroactive stat max reset. It's probably just a handful of people who have slightly higher than their correct stat maxes. But I should still fix this.

**Comment by ZaneDubya** [comment]
private void RetroactivelyCalculateAttributeMaxes() {
            CanoProgInitial initial = LegacyAssets.GetProgressionInitial((int)Race, (int)Class);
            // set initial maxes:
            StrengthMax = initial.StrengthMax;
            DefenseMax = initial.DefenseMax;
            AgilityMax = initial.AgilityMax;
            InitiativeMax = initial.InitiativeMax;
            // map 14 - "Blessed X or X, you may continue the quest":
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_HumanThief) == 1 && 
                (Race == ECharacterRace.Human || Class == ECharacterClass.Thief)) {
                StrengthMax += 1;
                DefenseMax += 1;
            }
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_OrcCleric) == 1 &&
                (Race == ECharacterRace.Orc || Class == ECharacterClass.Cleric)) {
                StrengthMax += 1;
                DefenseMax += 1;
            }
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_ElfBarb) == 1 &&
                (Race == ECharacterRace.Elf || Class == ECharacterClass.Barbarian)) {
                StrengthMax += 1;
                DefenseMax += 1;
            }
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_TrollRanger) == 1 &&
                (Race == ECharacterRace.Troll || Class == ECharacterClass.Ranger)) {
                StrengthMax += 1;
                DefenseMax += 1;
            }
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_DwarfKnight) == 1 &&
                (Race == ECharacterRace.Dwarf || Class == ECharacterClass.Knight)) {
                StrengthMax += 1;
                DefenseMax += 1;
            }
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_GnomeWizard) == 1 &&
                (Race == ECharacterRace.Gnome || Class == ECharacterClass.Wizard)) {
                StrengthMax += 1;
                DefenseMax += 1;
            }
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_HalflingKeyCleo) == 1 &&
                (Race == ECharacterRace.Halfling)) {
                StrengthMax += 1;
                DefenseMax += 1;
            }
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_GremlinPickCleo) == 1 &&
                (Race == ECharacterRace.Gremlin)) {
                StrengthMax += 1;
                DefenseMax += 1;
            }
            // map 20 - Visited Wyn's Fountain
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_WynFountain) == 1) {
                InitiativeMax += 3;
            }
            // map 24 - you can access just one of these bonuses:
            // orcs and trolls have access to strength:
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_Map24Str) == 1 &&
                (Race == ECharacterRace.Orc || Race == ECharacterRace.Troll)) {
                StrengthMax += 3;
            }
            // gremlins and dwarves have access to defense:
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_Map24Def) == 1 &&
                (Race == ECharacterRace.Gremlin || Race == ECharacterRace.Dwarf)) {
                DefenseMax += 3;
            }
            // elves and gnomes have access to agility:
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_Map24Agi) == 1 &&
                (Race == ECharacterRace.Elf || Race == ECharacterRace.Gnome)) {
                AgilityMax += 3;
            }
            // humans and halflings have access to initiative:
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_Map24Ini) == 1 &&
                (Race == ECharacterRace.Human || Race == ECharacterRace.Halfling)) {
                InitiativeMax += 3;
            }
            // map 25
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_BlackjackFountain) == 1) {
                AgilityMax += 3;
            }
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_CribbageFountain) == 1) {
                InitiativeMax += 3;
            }
            // map 26
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_Map26Dex) == 1) {
                // do nothing here - i do not cap dex
            }
            // map 31
            if (MapData.GetFlag(AMap.FlagTypeDungeon, AMap.FlagModAttr_DragonBreathFountain) == 1) {
                StrengthMax += 1;
                DefenseMax += 1;
                AgilityMax += 1;
                InitiativeMax += 1;
            }
            // cap attributes:
            if (Strength > StrengthMax) {
                _AttributePointsRemaining += (ushort)(Strength - StrengthMax);
                Strength = StrengthMax;
            }
            if (Defense > DefenseMax) {
                _AttributePointsRemaining += (ushort)(Defense - DefenseMax);
                Defense = DefenseMax;
            }
            if (Agility > AgilityMax) {
                _AttributePointsRemaining += (ushort)(Agility - AgilityMax);
                Agility = AgilityMax;
            }
            if (Initiative > InitiativeMax) {
                _AttributePointsRemaining += (ushort)(Initiative - InitiativeMax);
                Initiative = InitiativeMax;
            }
            /*int maxAttributePoints = (StrengthMax - Strength) + (DefenseMax - Defense) - (AgilityMax - Agility) - (InitiativeMax - Initiative);
            if (_AttributePointsRemaining > maxAttributePoints) {
                _AttributePointsRemaining = (ushort)maxAttributePoints;
            }*/
        }

**Comment by ZaneDubya** [comment]
Fix will be in Update 188
