### ISSUE TITLE
Deeds to add

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#440]
Opening Castlegate teleport.
Solving the Wizard's "GHOST" Challenge.
Returning the King to the Blackjack Fountain.
Forging the Flex Sword.
Defeating Arnakkian
You passed through 8 bless doors... maybe including "of X", where is the remaining doors the character can pass.
Blue Gem
Green Gem
Yellow Gem
Red Gem
Golden Boat
Moon Prism
Building the Rainbow Bridge.
Defeating Wind Elemental
Defeating En-li-Kil
Finding Tobraine's Tomb.

Also: 
Thoughts on giving clues to remaining deeds?
Showing percentage of map explored.

**Comment by ZaneDubya** [comment]
- [ ] Opening Castlegate teleport.
- [ ] Solving the Wizard's "GHOST" Challenge.
- [ ] Returning the King to the Blackjack Fountain.
- [ ] Forging the Flex Sword.
- [ ] Defeating Arnakkian
- [ ] You passed through 8 bless doors... maybe including "of X", where is the remaining doors the character can pass.
- [ ] Blue Gem
- [ ] Green Gem
- [ ] Yellow Gem
- [ ] Red Gem
- [ ] Golden Boat
- [ ] Moon Prism
- [ ] Building the Rainbow Bridge.
- [ ] Defeating Wind Elemental
- [ ] Defeating En-li-Kil
- [ ] Finding Tobraine's Tomb.

Also: 
- Thoughts on giving clues to remaining deeds? *Done.*
- Showing percentage of map explored. *Can't do easily.*

**Comment by ZaneDubya** [comment]
There are now 30 achievements plus the blessed door string. Nice! That's enough for Yserbius, I don't plan on adding any more. It was really interesting to go back into those map scripts, which I haven't touched in last summer. Thanks Revenge!
