### ISSUE TITLE
What to do with the rune prism?

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/CommunityKitPublic#451]
Passive skills must be equipped to be effective. The rune prism doesn't work, because rune reading is now a passive skill. Should I introduce a whole new category of skill - passive but can be active if used through an item? Or should I just get rid of the rune prism altogether...

**Comment by alerum68** [comment]
The rune prism is needed for those without a high enough trained skill of rune reading.

**Comment by ZaneDubya** [comment]
This is the least fun issue on the list of prioritized issues, but also the only thing that is actually broken. Prioritizing :(

**Comment by ZaneDubya** [comment]
Fixed!

**Comment by alerum68** [comment]
Rune Prism is still not working.

**Comment by ZaneDubya** [comment]
Ah, it is. But the sensor is not, and I should make the omni and sensor prisms purchaseable...
