### ISSUE TITLE
Highlight who is acting during combat.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/CommunityKitPublic#456]

**Comment by ZaneDubya** [comment]
Working on this!

**Comment by ZaneDubya** [comment]
Done, just needs some kind of highlight graphic. Maybe something from this game I worked on two years ago?
![Test](https://user-images.githubusercontent.com/7041719/57741770-e8cc3080-7683-11e9-9c9f-0578443e000e.png)

**Comment by alerum68** [comment]
I like the first box below the 0.

**Comment by ZaneDubya** [comment]
Finished, will push this evening.
