### ISSUE TITLE
Arming a weapon gives you +6 def

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#468]
With no other eq or rings on, arming the WHoD and the Flex Sword gave me a bonus of +6 def, which should not be there.  I'm wondering if this is linked to a skill bonus?  Testing in offline version with all spells and skills maxed didn't provide the +6 def bonus.

**Comment by ZaneDubya** [comment]
Excellent catch! UI will now correctly report Defense - it was getting an incorrect value from the buff update packet. Fixed in 192.
