### ISSUE TITLE
Zaika - Chat Channel History

### ISSUE THREAD

**Issue by jerryblade** [ZaneDubya/CommunityKitPublic#469]
Is there any way to make the chat logs semi-persistent? I LOVE that you added tabs so we can keep track of different chat channel traffic, but every single time we go from the dungeon to the inn or wherever, the history gets wiped. It would be awesome if that carried over at least until you log off!

**Comment by Wynder** [comment]
Upvoting this!

**Comment by ZaneDubya** [comment]
This will be in the guilds update, coming soon!

**Comment by ZaneDubya** [comment]
Coming in 192 today.

**Comment by jerryblade** [comment]
HUZZAH!
