### ISSUE TITLE
Spell duration isn't reset when recast

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#471]
If you cast a spell, wait a few rounds, then cast again it should reset the spell timer back to 0, giving you the full number of turns available from the second cast, not the first.  Currently if you cast the spell again before it expires it will have no affect on the duration of the spell, so you are still in turn 3 of the spell, not 0.

Also make sure this doesn't remove the ability of certain spells to "stackable".

**Comment by ZaneDubya** [comment]
This is actually the game’s default behavior.

**Comment by ZaneDubya** [comment]
Relevant: https://arstechnica.com/gaming/2019/05/world-of-warcraft-classic-beta-testers-are-reporting-vanilla-wow-features-as-bugs/

**Comment by ZaneDubya** [comment]
And a comment from that article:
> Vanilla gameplay was kind of a hot mess that got a lot of latitude . . . . So much of it felt designed to be hostile to players. Getting 40 people together to do a raid is just such a nightmarish idea...

**Comment by ZaneDubya** [comment]
But honestly I've thought about doing this as well...

**Comment by ZaneDubya** [comment]
Part of #473

**Comment by alerum68** [comment]
I think it would be a good addition. The way it works now you're spell will drop for 1 round no matter what you do.

**Comment by ZaneDubya** [comment]
Of course, this also keeps debuff durations from being reset ;)

**Comment by ZaneDubya** [comment]
added in 195
