### ISSUE TITLE
Multiplier for EXP

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#472]
Revisit previous change (Yeah I know you hate to do it), but let's MULTIPLY the amount of EXP given when in groups.  For each person multiply exp given by 3, and if full group then round up 10.

**Comment by ZaneDubya** [comment]
1 party member: 1x
2 party members: 1.5x/p
3 party members: 1.75x/p
4 party members: 2x/p

**Comment by alerum68** [comment]
How about a bit more? 1x more for each party member? 
1=1x
2=2x
3=3x
4=4x

**Comment by ZaneDubya** [comment]
coming in 192 later today.
