### ISSUE TITLE
Show active buffs in UI

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/CommunityKitPublic#473]

**Comment by alerum68** [comment]
Good! I never liked that backfire was the only big shown.

**Comment by ZaneDubya** [comment]
Prioritized.

**Comment by ZaneDubya** [comment]
So close!
<img width="968" alt="Screen Shot 2019-06-04 at 6 39 25 PM" src="https://user-images.githubusercontent.com/7041719/58920508-27d82980-86f8-11e9-9738-a6cbe7a6cde6.png">

**Comment by ZaneDubya** [comment]
Done, will be in 19D
