### ISSUE TITLE
Client Slow Loading and Hanging

### ISSUE THREAD

**Issue by jerryblade** [ZaneDubya/CommunityKitPublic#482]
All of a sudden, with the latest patch, I am getting some strange behavior. On my "Fast" PC, the client takes 1-2 mins to just load and confirm whether I need a patch. Then it takes another 1-2 minutes for the patcher to load and confirm if i do or dont need a patch. Once that happens, it's another 1-2 mins for the Client to officially load... What could be causing this behavior? I thought it might by my virus checker, but the directory and both executables are exempted already. On my "Slow" PC, there is no change. 

Also, every few minutes, the application "hangs" for 30sec...

Crazy! :)

**Comment by ZaneDubya** [comment]
You just told me in the game that you fixed it! I'll have to add this information to the website! 

* Downloaded fresh from Website.
* Removed 'Run as Administrator'
* Removed anti virus exemptions.
