### ISSUE TITLE
Better guild management

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/CommunityKitPublic#499]
- [x] Change rank titles
- [x] Change rank permissions
- [x] Opt out of accepting requests

**Comment by ZaneDubya** [comment]
So close!

<img width="980" alt="Screen Shot 2019-06-04 at 8 22 43 PM" src="https://user-images.githubusercontent.com/7041719/58923748-85737280-8706-11e9-8833-8c76bd48157b.png">

**Comment by alerum68** [comment]
Hehehe... You're giving me a lot of trust with my own name for roles. 😁

**Comment by ZaneDubya** [comment]
No reason I shouldn't trust you. :)

**Comment by ZaneDubya** [comment]
Done! Needs testing. Please try to break this!
