### ISSUE TITLE
Cannot Log On

### ISSUE THREAD

**Issue by jerryblade** [ZaneDubya/CommunityKitPublic#502]
All of a sudden, the Client is telling my my password is bad, but I know I am using the right one.

**Comment by jerryblade** [comment]
After a bit more experimentation, it appears that when I type in the correct password, the client says "That is not a valid password". If I try a longer more complex but incorrect password, it says "Unable to log in. Is the account name and/or password correct?". I am guessing that the password requirements changed, and now the password I have been using is no longer legitimate, effectively locking me out of my account :(

**Comment by ZaneDubya** [comment]
Whoops! I'm sorry. I've restored your access (And access for everyone who has a similar password).

As they say, don't test in production!
