### ISSUE TITLE
Last Post counter wrong in main BB page

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#505]
![image](https://user-images.githubusercontent.com/35239228/58768675-cf682700-8553-11e9-9a4b-17c05f1a3fcb.png)

All groups have last post on different dates, excluding General.  I think the other groups are displaying Last Post date for just the General chat, not their own.

**Comment by ZaneDubya** [comment]
ooooooooooh, that's a good one.

**Comment by ZaneDubya** [comment]
Fixed, coming today.
