### ISSUE TITLE
Fix players resisting spells in Challenge battles

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/CommunityKitPublic#510]
Per REVENGE, players should not be resisting spells in PvP combat (well, actually he said that all spells should succeed until backfire lands).
- [ ] Compare against videos from the original game?
- [ ] Is resistance too high in PvM as well?

**Comment by alerum68** [comment]
I think resistance to spells remains at 0% throughout the battle.  Backfire reduced the chance of a spell working.  Even if the Backfire isn't successful, it will diminish the chance of some spells working, but until it's cast on you, you will have 100% success on spells.  BUFFS seems to still take 100% of the time after an unsuccessful backfire is cast, while debuffs against your opponent will have a chance to fail.  I don't have actual values that they're affected by on a failed or a successful backfire though.

**Comment by ZaneDubya** [comment]
https://www.twitch.tv/videos/435107395?t=07s
