### ISSUE TITLE
Inappropriate Pass Through Walls Scenarios

### ISSUE THREAD

**Issue by Ninjirate** [ZaneDubya/CommunityKitPublic#517]
I do not want to post the full details of this bug publicly. I have found a few scenarios that allow you to pass through walls and doors that should otherwise not occur. I'm finding that they all seem to be specific to the same mechanism and have similar steps to recreate in each scenario so it should be easy for you to track down and eliminate.

This bug could allow a person to gain unfair advantage in game by accessing areas of the game that should otherwise unavailable yet or should be completely inaccessible which causes a player to become stuck in the map.

I am a professional software tester. Please contact me for a walkthrough in game or for detailed steps to recreate.

**Comment by Ninjirate** [comment]
My character Ceoleif is now stuck on a map in a part that should not be accessible and I'm stuck.. Help :)

**Comment by ZaneDubya** [comment]
Fixed, in testing.

**Comment by ZaneDubya** [comment]
Closing as fixed!
