### ISSUE TITLE
/help command enhancements

### ISSUE THREAD

**Issue by Ninjirate** [ZaneDubya/CommunityKitPublic#518]
When invoking the /help command from chat window in tavern or from dungeon, the only commands listed for reference are guild related functions. This list should be enhanced to include other chat box command parameters available for current role type. 

Helpful ones would be how to access the difference commands to chat: /a, /c, etc

**Comment by ZaneDubya** [comment]
Ah, this is because /help only returns the commands that are handled by the server - the various chat mode switching commands are handled by the client. I should be able to add some dummy server commands to be included in the help command. Thanks!

**Comment by ZaneDubya** [comment]
in testing.
