### ISSUE TITLE
Easily Change Chat Back To /s (say) type

### ISSUE THREAD

**Issue by Ninjirate** [ZaneDubya/CommunityKitPublic#519]
New users can encounter a challenge if they are not already familiar with the game chat commands. One thing that seems to happen is once someone clicks on another persons name in the tavern, it automatically changes to a personal message type specific to that player. Someone then has no easy way to go back to normal /c (say) conversation type without knowing the commands. 

One easy way to fix this might be if the backspace is pressed while on an empty chat field, change the selected chat type back to /c (say) by default. 

This happened to me often over the last few days and I just now today figured out how to use the commands. This should be easier to figure out/use for newbies.

**Comment by ZaneDubya** [comment]
Fixed in UiLegacyTextEntryChat.cs at line 150: 

On keyboard event down when current chat mode is any of REVERTABLE_MSG_TYPES, revert to last non-REVERTABLE_MSG_TYPES chat mode.

Currently, REVERTABLE_MSG_TYPES only includes whisper:


        /// <summary>
        /// These message types will be reverted to a saved message type when the player presses backspace on an empty chat field.
        /// </summary>
        private static EMessageType[] REVERTABLE_MSG_TYPES = {
            EMessageType.Whisper,
        };

**Comment by ZaneDubya** [comment]
In testing.
