### ISSUE TITLE
Item Removal Script Not Being Processed For All Party Members - LV20 Thieves Guild Key Entrance

### ISSUE THREAD

**Issue by Ninjirate** [ZaneDubya/CommunityKitPublic#520]
When entering the LV20 door in the main dungeon entrance and there are multiple party members who have Cleowyn Items existing in their pack. For some reason, when you enter this door the script to remove Cleowyn Keys and quest items is only executed on one party member at a time. In order for other party members to be affected, you have to go through this entrance multiple times with the same party members. It's acting like the programming is checking for players with items, matching the first one, performing the removal items process then not looping back for other party members.

**Comment by ZaneDubya** [comment]
Thanks for reporting! Looking into this now.

**Comment by ZaneDubya** [comment]
Here's how it works right now:

1. Map script checks to see if ALL party members are 20+. If so:
2. Map script checks EACH player in sequence for thieves' key. If THE PLAYER BEING CHECKED has the thieves' key, the door is unlocked for THAT player(a permanent flag is set allowing passage) and THAT player has any cleowyn's gear removed. If a player does not have the thieves' key, that player retains their cleowyn's gear and the permanent flag remains unset, indicating that the door remains locked for that player.
3. Map script allows passage through the door if permanent flag allowing passage for the leader is flag.

Here's how I could change it (see bold changes in item 2):

1. Map script checks to see if ALL party members are 20+. If so:
2. Map script checks **ALL** players in sequence for thieves' key. If **ANY** player has the thieves' key, the door is permanently unlocked for **ALL** players (a permanent flag is set allowing passage) and **ALL** players have any cleowyn's gear removed.
3. Map script allows passage through the door if permanent flag allowing passage for the leader is flag.

Would that work?

**Comment by ZaneDubya** [comment]
After thinking about this over several cups of coffee, I've come to the conclusion that the best thing I can do with this bug is to rewrite the original map script.

The original code is as follows:

        private void FnDOORMESS_0B(ServerPlayer player, MapEventType type, bool doMsgs) {
            int ax = 0, bx = 0, cx = 0, dx = 0, si = 0, di = 0, tmp = 0;
            L0000: // BEGIN;
            L0003: ax = CheckLevel(player, 0x0014);
            L0011: if (JumpNotEqual) goto L0016;
            L0013: goto L011F;
            L0016: Compare(GetFlag(player, FlagTypeDungeon, FlagUnlockedLabyrinthDoor), 0x0001);
            L002A: if (JumpNotEqual) goto L005A;
            L002C: ShowMessage(player, doMsgs, String0504); // This room contains the gateway to the Labyrinth.
            L0039: SetWallPassable(player, GetCurrentTile(player), GetFacing(player), 0x01);
            L0057: goto L011D;
            L005A: ax = HasItem(player, ItemThievesKey);
            L0068: if (JumpNotEqual) goto L006D;
            L006A: goto L0110;
            L006D: ShowMessage(player, doMsgs, String0535); // The Thieves' Key unlocks this door!
            L007A: ShowMessage(player, doMsgs, String0559); // This room contains the gateway to the Labyrinth.
            L0087: SetFlag(player, FlagTypeDungeon, FlagUnlockedLabyrinthDoor, 0x01);
            L009C: RemoveItem(player, ItemThievesKey);
            L00A8: RemoveItem(player, ItemKingCleowynsLockpick);
            L00B4: RemoveItem(player, ItemKingCleowynsKey);
            L00C0: RemoveItem(player, ItemKeyToCleowynsPalace);
            L00CC: RemoveItem(player, ItemKingsDomicileKey);
            L00D8: RemoveItem(player, ItemLavaKey);
            L00E4: RemoveItem(player, ItemKingsRing);
            L00F0: SetWallPassable(player, GetCurrentTile(player), GetFacing(player), 0x01);
            L010E: goto L011D;
            L0110: ShowMessage(player, doMsgs, String058A); // The Thieves' Key is needed to unlock this door.
            L011D: goto L0156;
            L011F: ShowMessage(player, doMsgs, String05BA); // The Thieves' Key is needed to unlock this door.
            L012C: ShowMessage(player, doMsgs, String05EA); // Only heroes of the twentieth level or higher may venture beyond this door.
            L0139: SetWallPassable(player, GetCurrentTile(player), GetFacing(player), 0x00);
            L0156: return; // RETURN;
        }

Which is now replaced by:



        private void FnDOORMESS_0B(ServerPlayer player, MapEventType type, bool doMsgs) {
            ShowMessage(player, doMsgs, String0504); // This room contains the gateway to the Labyrinth.
            // party level check:
            if (CheckLevel(player, 20) == 0) {
                ShowMessage(player, doMsgs, String05EA); // Only heroes of the twentieth level or higher may venture beyond this door.
                return;
            }
            // check if this player has already unlocked the door:
            if (Compare(GetFlag(player, FlagTypeDungeon, FlagUnlockedLabyrinthDoor), 0x0001)) {
                if (player.IsPartyLeader) {
                    ShowMessage(player, doMsgs, "The door is unlocked. The Labyrinth is open to you.");
                    SetWallPassable(player, GetCurrentTile(player), GetFacing(player), 0x01);
                }
                else {
                    ShowMessage(player, doMsgs, "You previously unlocked this door. When you lead a party, it will open for you.");
                }
                return;
            }
            // we haven't already unlocked the door. Check for thieves' key:
            if (HasItem(player, ItemThievesKey) == 1) {
                ShowMessage(player, doMsgs, String0535); // The Thieves' Key unlocks this door!
                ShowMessage(player, doMsgs, "You notice that your pack seems much lighter. To your surprise, Cleowyn's vestments and a number of keys have disappeared");
                SetFlag(player, FlagTypeDungeon, FlagUnlockedLabyrinthDoor, 0x01);
                RemoveItem(player, ItemThievesKey);
                RemoveItem(player, ItemKingCleowynsLockpick);
                RemoveItem(player, ItemKingCleowynsKey);
                RemoveItem(player, ItemKeyToCleowynsPalace);
                RemoveItem(player, ItemKingsDomicileKey);
                RemoveItem(player, ItemLavaKey);
                RemoveItem(player, ItemKingsRing);
                SetWallPassable(player, GetCurrentTile(player), GetFacing(player), 0x01);
                return;
            }
            // door is locked, no thieves' key:
            ShowMessage(player, doMsgs, String05BA); // The Thieves' Key is needed to unlock this door.
        }
