### ISSUE TITLE
Getting Crown

### ISSUE THREAD

**Issue by aaronhenson** [ZaneDubya/CommunityKitPublic#845]
E key wont open the back secret room with the crown. Oddly O opens the doors that come before it. And I *think* my E key was taken in the room where I should have? Something like that. Anyway, someone might want to verify the vowel keys. E specifically.

Or Im just an idiot. It has been 25+ years.

**Comment by ZaneDubya** [comment]
@aaronhenson Hey Aaron! Welcome (and welcome to GitHub :) )

Thanks for this report. Quick question - are you following Tiger's guide? https://medievalands.com/help/tsoy-walk-tiger.pdf

**Comment by aaronhenson** [comment]
I checked both walkthroughs but I finally got in after getting all the keys
a second time.

**Comment by ZaneDubya** [comment]
Glad to hear this was resolved - sorry for the difficulty - and good luck moving forward with that quest chain!
