### ISSUE TITLE
Old achievements not appearing

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/CommunityKitPublic#846]
The follow task have been completed, but not marked in Achievements.  Not sure if it was because they were completed before the Achievements went into affect or not.  Following ones are not shown:

Lunar Reflections
The Rainbow Gems
Champion's Blade
Solar Barge
Rainbow Bridge

**Comment by ZaneDubya** [comment]
@alerum68 Thanks for letting me know! I'll be looking into this...

**Comment by ZaneDubya** [comment]
Fixed!
