### ISSUE TITLE
Twinion: Able to cast Dissipate on non-undead enemies

### ISSUE THREAD

**Issue by Stormborg** [ZaneDubya/CommunityKitPublic#852]
We tested this in the Coliseum
![DissipateBug](https://user-images.githubusercontent.com/6412683/93008614-a733ea00-f544-11ea-853f-d348e9cfd0c3.JPG)

**Comment by ZaneDubya** [comment]
Thanks @Stormborg, tracking this now. :)

**Comment by ZaneDubya** [comment]
Fixed.
