### ISSUE TITLE
Track player interaction with item drops

### ISSUE THREAD

**Issue by ElDudorino0** [ZaneDubya/CommunityKitPublic#866]
Zane: I can definitely adjust the health potions downwards. I should be collecting better analytics.

It would be interesting to know how often items are "taken" by the player. It's ok to have a bunch of trash - but you should be finding upgrades at a semi-regular cadence.

ElDudorino: Can you track whether an item was moved to the player's inventory and what type of item it was?  Depending on how annoying it is to code, maybe minimum viable would be to just track how often an item is moved from its slot on the loot screen or right-clicked in the loot menu?

**Comment by ZaneDubya** [comment]
Added in local dev.
