### ISSUE TITLE
Players sometimes appear on map or in 3D view when they aren't there

### ISSUE THREAD

**Issue by ElDudorino0** [ZaneDubya/CommunityKitPublic#869]
Sometimes a player outline is visible in the 3D view when no player is actually located there.  Possibly only occurs near map exits?
![image](https://user-images.githubusercontent.com/71567817/93728804-a8da5f00-fb8f-11ea-8565-04f9fccc7cb7.png)

Also, dragoneye74 says: I have notices a few Caspers too! Also on the map screen, will show someone is there, but they have left.  I have notices most caspers in front of doors. A couple of times I was chatting with someone, they are still shown visible on the map, like this.
![image](https://user-images.githubusercontent.com/71567817/93728875-f787f900-fb8f-11ea-9899-1316bebbd859.png)

**Comment by ZaneDubya** [comment]
I recognize this is happening but can't seem to trigger it. Possible ideas:
- Has something to do with players leaving/joining a party.
- Has something to do with teleports (doors that move you from one map to another).

**Comment by ZaneDubya** [comment]
Possible this has something to do with AFK.

**Comment by ZaneDubya** [comment]
Added new functionality that hides a player in the dungeon map when AFK.

**Comment by ZaneDubya** [comment]
DragonEye: I have been able to reproduce the Ghost. Was playing in the Dev server, was pulled away long enough to go AFK. When I came back I see this.

ElDudorino: So you're seeing your own past?

**Comment by ZaneDubya** [comment]
Should be fixed!
