### ISSUE TITLE
Returning to Dungeon Entrance from Labyrinth faces the player the wrong way

### ISSUE THREAD

**Issue by ElDudorino0** [ZaneDubya/CommunityKitPublic#870]
Per dragoneye74:
I just came across another strage thing. Maybe the game is supposed to work this way. Went into the Labyrinth I through the normal door. Came back through and I was pointed directly at the door again. All other doors when you go through them, you are pointed in the same direction you were originally facing.

![image](https://user-images.githubusercontent.com/71567817/93728908-1be3d580-fb90-11ea-98e4-f0ecf5b3adc3.png)

**Comment by ZaneDubya** [comment]
Fixed!
