### ISSUE TITLE
(Dev server) Death Darts sometimes does not damage stacks of 1

### ISSUE THREAD

**Issue by ElDudorino0** [ZaneDubya/CommunityKitPublic#878]
When casting Death Darts on the dev server, I've found that sometimes I am not dealing damage to stacks of 1 but I am consistently hitting stacks of 2 or more.

Sometimes I have no problem hitting a stack of 1 and I have not been able to figure out what causes them to be missed in only certain cases.  Sometimes when I fail to hit a stack of 1, I cast again and miss again but then cast a third or fourth time and hit them.

Is it possible that something is wrong with the Resist Magic / Saving Throw mechanic if stack size is 1?
![image](https://user-images.githubusercontent.com/71567817/94378523-48e83900-00f8-11eb-80bc-55eba7eca349.png)

**Comment by ZaneDubya** [comment]
Thanks @ElDudorino0 :)

**Comment by ZaneDubya** [comment]
Fixed!
