### ISSUE TITLE
When enemies heal themselves, it always says they are healed to maximum

### ISSUE THREAD

**Issue by ElDudorino0** [ZaneDubya/CommunityKitPublic#879]
This is a visual bug; enemies who cast Heal on themselves display a message saying that their health has been restored to maximum but their health has not necessarily been fully restored.
![image](https://user-images.githubusercontent.com/71567817/94881807-55d89580-0434-11eb-95ab-5c7c85a22b10.png)

**Comment by ZaneDubya** [comment]
Working on this...

**Comment by ZaneDubya** [comment]
Fixed.
