### ISSUE TITLE
Stats improvements not working, at least visually, until you re-equip gear that provides bonus in same stat

### ISSUE THREAD

**Issue by Stormborg** [ZaneDubya/CommunityKitPublic#992]
Yserbius 
Human Cleric
Base Initiative is 9
Wearing Dynamic Ring providing +3 Initiative

I forgot which map it is, but there is a space where you enter it and get a permanent Initiative stat increase of +3

After seeing the text, Initiative score in gear/stats window is still 12
Continued to play; leaving and returning, still 12
Put new accessory in place of Dynamic Ring, Initiative remains at 12
Put Dynamic Ring back on, Initiative is now at 15

A similar thing happened after getting the Staff skill in Thieves Den.

Wielding Holy Halberd without Staff skill
Acquire skill in Thieves Den, no bonus icon.
Continue to play; leaving and returning, no bonus icon.
Swapped weapon to a bow (also got Archery from Thieves Den), Archery bonus icon appears
Swapped weapon to Holy Halberd, Staff bonus icon now appears.

**Comment by ZaneDubya** [comment]
Not exactly the same, but related to #989

**Comment by ZaneDubya** [comment]
Fixed in dev.
